Definition Problems Fixed
Most of the browsers having problem with definitions. Because the javascript variables didn't defined using let or var or const, getting error and not loading page truly. 

ReferenceError: layers_positions is not defined